apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: pulumi-deployment
  title: Create Infrastructure with Pulumi Deployments
  description: |
    Create a new Pulumi project with Pulumi Deployments configured
    for automatic deployments on git push and PR previews.
  tags:
  - pulumi
  - pulumi-deployments
  - gitops
  - aws
spec:
  owner: user:guest
  type: infrastructure
  parameters:
  - title: Provide project information
    required:
    - name
    - owner
    properties:
      name:
        title: Name
        type: string
        description: Unique name of the Pulumi project.
        ui:
          field: EntityNamePicker
      description:
        title: Description
        type: string
        description: Tell us more about this project.
      system:
        title: System
        type: string
        description: System this component belongs to.
        ui:field: EntityPicker
        ui:options:
          catalogFilter:
            kind:
            - System
      owner:
        title: Owner
        type: string
        description: Owner of the component
        ui:field: OwnerPicker
        ui:options:
          allowedKinds:
          - Group
  - title: Configure Pulumi
    required:
    - stack
    - organization
    properties:
      organization:
        title: Organization
        type: string
        description: The Pulumi organization to use for the Pulumi project
      stack:
        title: Select stack
        type: string
        enum:
        - dev
        - staging
        - prod
        enumNames:
        - Development
        - Staging
        - Production
        description: The Pulumi stack to use
      awsRegion:
        title: AWS Region
        type: string
        default: us-west-2
        description: AWS region for deployment
  - title: Configure Pulumi Deployments
    properties:
      enableDeployments:
        title: Enable Pulumi Deployments
        type: boolean
        default: true
        description: Configure automatic deployments via Pulumi Deployments
      deployOnCommit:
        title: Deploy on Commit
        type: boolean
        default: true
        description: Automatically deploy when commits are pushed to the default branch
      previewPullRequests:
        title: Preview Pull Requests
        type: boolean
        default: true
        description: Automatically run preview on pull requests
      enableCaching:
        title: Enable Dependency Caching
        type: boolean
        default: true
        description: Cache dependencies for faster deployments
      awsOidcRoleArn:
        title: AWS OIDC Role ARN (Optional)
        type: string
        description: AWS IAM Role ARN for OIDC authentication (e.g., arn:aws:iam::123456789012:role/PulumiDeployRole)
  - title: Choose a location
    required:
    - repoUrl
    properties:
      repoUrl:
        title: Repository Location
        type: string
        ui:field: RepoUrlPicker
        ui:options:
          allowedHosts:
          - github.com
  steps:
  - id: fetch-base
    name: Fetch Base Template
    action: fetch:template
    input:
      url: ./template
      values:
        name: ${{ parameters.name }}
        description: ${{ parameters.description }}
        destination: ${{ parameters.repoUrl | parseRepoUrl }}
        organization: ${{ parameters.organization }}
        stack: ${{ parameters.stack }}
        owner: ${{ parameters.owner }}
        system: ${{ parameters.system }}
        awsRegion: ${{ parameters.awsRegion }}

  - id: pulumi-new
    name: Initialize Pulumi Project
    action: pulumi:new
    input:
      name: ${{ parameters.name }}
      description: ${{ parameters.description }}
      stack: ${{ parameters.stack }}
      organization: ${{ parameters.organization }}
      template: aws-typescript
      folder: .
      config:
        "aws:region": ${{ parameters.awsRegion }}

  - id: publish
    name: Publish to GitHub
    action: publish:github
    input:
      repoVisibility: public
      description: "Infrastructure project: ${{ parameters.description }}"
      repoUrl: ${{ parameters.repoUrl }}
      defaultBranch: main
      requiredApprovingReviewCount: 0
      protectDefaultBranch: false

  - id: wait-for-repo
    name: Wait for repository
    action: debug:wait
    input:
      seconds: 10

  - id: configure-deployment
    name: Configure Pulumi Deployments
    if: ${{ parameters.enableDeployments }}
    action: pulumi:deployment:config
    input:
      organization: ${{ parameters.organization }}
      project: ${{ parameters.name }}
      stack: ${{ parameters.stack }}
      sourceContext:
        git:
          repoUrl: "https://github.com/${{ (parameters.repoUrl | parseRepoUrl)['owner'] }}/${{ (parameters.repoUrl | parseRepoUrl)['repo'] }}.git"
          branch: main
          repoDir: .
      github:
        repository: "${{ (parameters.repoUrl | parseRepoUrl)['owner'] }}/${{ (parameters.repoUrl | parseRepoUrl)['repo'] }}"
        deployCommits: ${{ parameters.deployOnCommit }}
        previewPullRequests: ${{ parameters.previewPullRequests }}
      operationContext:
        preRunCommands:
        - npm install
        oidc:
          aws:
            roleArn: ${{ parameters.awsOidcRoleArn if parameters.awsOidcRoleArn else '' }}
      cacheOptions:
        enable: ${{ parameters.enableCaching }}

  - id: initial-deployment
    name: Trigger Initial Deployment
    if: ${{ parameters.enableDeployments }}
    action: pulumi:deployment:run
    input:
      organization: ${{ parameters.organization }}
      project: ${{ parameters.name }}
      stack: ${{ parameters.stack }}
      operation: update
      inheritSettings: true

  - id: register
    name: Register in Catalog
    action: catalog:register
    input:
      repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
      catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
    - title: Source Code Repository
      url: ${{ steps['publish'].output.repoContentsUrl }}
    - title: Pulumi Cloud Console
      url: "https://app.pulumi.com/${{ parameters.organization }}/${{ parameters.name }}/${{ parameters.stack }}"
    - title: Deployment Settings
      url: "https://app.pulumi.com/${{ parameters.organization }}/${{ parameters.name }}/${{ parameters.stack }}/settings/deploy"
    - title: Open in Catalog
      icon: catalog
      entityRef: ${{ steps['register'].output.entityRef }}
