name: Build Microservice and Generate Kubernetes manifests

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - "kustomize/**"

permissions: read-all

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      packages: write
    {% raw %}
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        name: Checkout
      - name: Log in to the Container registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
    {% endraw %}
      - name: Build and push Docker image
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825 # v4.1.1
        with:
          context: .
          push: true
          file: Dockerfile
          tags: ghcr.io/${{values.destination.owner}}/${{values.name}}:${{ '${{ github.sha }}' }},ghcr.io/${{values.destination.owner}}/${{values.name}}:latest

  generate:
    name: Generate Kubernetes manifests
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        name: Checkout
      - uses: imranismail/setup-kustomize@6691bdeb1b0a3286fb7f70fd1423c10e81e5375f # v2.0.0
        name: Setup Kustomize
      - run: |
          kustomize edit set image goapp=ghcr.io/${{values.destination.owner}}/${{values.name}}:${{ '${{ github.sha }}' }}
          cat kustomization.yaml
          git config --local user.email "action@github.com"
          git config --local user.name "Deploy Action"
          git commit -am "change image tag"
        working-directory: kustomize
        name: Update image tag
      {%- if values.scanner == 'trivy' %}
      - run: |
          kustomize build . -o $RUNNER_TEMP/test.yaml
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.44.0
          trivy config  $RUNNER_TEMP/test.yaml  --exit-code 0
        name: Check for misconfigurations
        working-directory: kustomize
      {%- endif %}
      - name: push
        uses: ad-m/github-push-action@master
