apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - services.yaml

namespace: ${{values.name}}

images:
  - name: goapp
    newName: goapp
    newTag: v1
