name: CI

on:
  push:
    branches:
    - main
    tags-ignore:
    - v*
    - sdk/*
    - "**"
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        fetch-depth: 0
    - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
      with:
        node-version: '20.x'
    - name: yarn install
      uses: backstage/actions/yarn-install@25145dd4117d50e1da9330e9ed2893bc6b75373e # v0.6.15
      with:
        cache-prefix: ${{ runner.os }}-v20.x
    - run: yarn lint
    - run: yarn tsc
    #- run: yarn test
    - run: yarn build:all
